### ISSUE TITLE
Original map project file

### ISSUE THREAD

**Issue by BigPino67** [Chenzo/sea-of-thieves-map-map#1]
Can you share the original map file (I mean photoshop project or gimp project with different layers) ?

There is some island that Rare has moved and this map is not up to date.

Thank you

**Comment by Chenzo** [comment]
Wait. What island is wrong/missing?

**Comment by BigPino67** [comment]
Spoils of plenty store have move next to keel haul fort!

**Comment by Chenzo** [comment]
Ok. Let me check that in a few

**Comment by Chenzo** [comment]
Re-Rendering the map is a bear

**Comment by BigPino67** [comment]
That's why i'm interested to get the map project file because I will make some changes for my needs!

**Comment by Chenzo** [comment]
ok, it was wrong. (It was a new place since the map was updated, I just dropped it in the wrong spot, for some reason.)

I've updated this repo with new tiles, (and the new map) I also updated the location in the other project and am currently uploading them all. (15k files... ooof.) Once it's there, I'll update the app and it should be good to go.

I'm reluctant to make the PSD public. Also, it's LARGE, like 650megs. I could perhaps send it to you but I'm not entirely sure what the best method for that would be.

**Comment by BigPino67** [comment]
My first need is too remove island names on the map. I will use DivIcon instead!
2nd is to modify the background and lines.

For the PSD file, you can drop somewhere public but with a private link like https://wetransfer.com/

**Comment by Chenzo** [comment]
Balls, my map numbers are off now... by 1... LOL.

Also, these islands aren't cut out. They're just screenshots.

**Comment by Chenzo** [comment]
Also, I'm not using mapbox, are you?

**Comment by BigPino67** [comment]
Maybe because you add the red seas!

**Comment by BigPino67** [comment]
No, i'm not!

**Comment by Chenzo** [comment]
Are you planning on Localizing this? I was never sure on how to do the text. I would love to set this one up to be localized. 

The problem with having the islands as markers is that markers don't scale. So it would look weird zoomed out, ya know?

Also, I figured out what was wrong with my map... I made tiles from the map at the wrong size.

**Comment by BigPino67** [comment]
Yes i'm planning to localize it but i will do this only when i've completed the french localization. To do so, the first parameter has to be the locale string. I'm not that good white htaccess file but i suppose i it's the way to make it works!

About the div markers, you can hide then when you are too much zoomed out!

The tiles are not correct presently! Reply me when they are OK!

**Comment by Chenzo** [comment]
Wait. They should be good now? You might need to hit refresh. Or clear your cache?

Vince
chenzorama@hotmail.com

________________________________

**Comment by Chenzo** [comment]
Now I see why you want to remove the island names from the map itself. I had always thought to get new map files from a French game...

Hmmm... let me think about the URL to pull the language... https://seaofthievesmap.chenzorama.com/fr/ yeah? Then we'd just need in this file:

https://github.com/Chenzo/sea-of-thieves-map/blob/master/src/js/modules/island_data.js

to have the titles with FR versions... like

```
{
        "loc": [-41.819753270587555, 62.927539082707604],
        "title": "Lone Cove",
        "title_fr": "FRENCH HERE",
        radius: 3,
        pigs: true,
        snakes: true
    }
```

**Comment by Chenzo** [comment]
I wonder if we can't just overlay the french ingame text over the titles.

**Comment by BigPino67** [comment]
I do really prefer using DivIcon instead of images, if something changes, will be easier to change only the parameter file instead of regenerating the tiles.

I am making a huge database for the game.

I'm not using your CDN path, I download the tiles!

**Comment by Chenzo** [comment]
Yeah, like I said, I couldn't get it to look good with the islands as markers.

Good luck getting it all to work. I'd love to see whatever you've done! Let me know if there's anything I can do to help.

**Comment by BigPino67** [comment]
About localizing, you have 2 choices, loading the localized file from the page parameter at it's loading or doing a huge parameter file with every languages!

**Comment by BigPino67** [comment]
Join this channel on discord and i'll give you a link : https://discord.gg/AYVZa

**Comment by Chenzo** [comment]
you could just do a fr.json or a de.json with overrides. That would be the simplest, in my mind. 

I also wonder if you can't just use divicon to drop text on the map and cover the english with the chosen language.

**Comment by Chenzo** [comment]
You'd have to scale the text onZoom though.

**Comment by BigPino67** [comment]
It doesn't cover so well, but I prefer divIcon to create some action with it!

**Comment by BigPino67** [comment]
Can you update the tiles repo ?

**Comment by Chenzo** [comment]
I did? https://github.com/Chenzo/sea-of-thieves-map-map Updated 4 hours ago.

this is the map image I made the tiles from https://github.com/Chenzo/sea-of-thieves-map-map/blob/master/sot_map_v2.4_2x.jpg

(i'll join the discord a little later)

**Comment by BigPino67** [comment]
OK, i forgot to clear the cache, the tiles are now OK.

The only problem I have for the moment is the alignment of DivIcon is not automatically set when i zoom in or out. I believe I will have to loop throught all the DivIcons in the layer to set i manually! :(

**Comment by BigPino67** [comment]
The discord link may have expire. Here's another one that will lasts for 1 day : https://discord.gg/nj7828

**Comment by Chenzo** [comment]
Hey... it's dead. lol... might be only 12 hours. I should be around for most of the night if you want to try one more time.

**Comment by BigPino67** [comment]
https://discord.gg/KEXtXz
